/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig_1.h"
#include "VRx_aliases.h"
#include "VRx.h"
#include "UART_DEBUG.h"
#include "AMux_1.h"
#include "VRy_aliases.h"
#include "VRy.h"
#include "isr_adc.h"
#include "UART_MOVI.h"
#include "isr_rx_movi.h"
#include "Clock_Movi.h"
#include "Looptimer.h"
#include "isr_Looptimer.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "EEPROM_CONFIG.h"
#include "UART_SBC.h"
#include "isr_rx_sbc.h"
#include "Pin_Debug_Tick_aliases.h"
#include "Pin_Debug_Tick.h"
#include "Pin_Debug_SuperLoop_aliases.h"
#include "Pin_Debug_SuperLoop.h"
#include "Pin_Debug_CoarseCentroid_aliases.h"
#include "Pin_Debug_CoarseCentroid.h"
#include "Pin_Debug_GimbalComms_aliases.h"
#include "Pin_Debug_GimbalComms.h"
#include "Pin_Debug_SBCComms_aliases.h"
#include "Pin_Debug_SBCComms.h"
#include "Clock_MCU.h"
#include "Pin_SwitchAuto_aliases.h"
#include "Pin_SwitchAuto.h"
#include "VDAC8_3v3Ref.h"
#include "USBFS_DEBUG.h"
#include "USBFS_DEBUG_audio.h"
#include "USBFS_DEBUG_cdc.h"
#include "USBFS_DEBUG_hid.h"
#include "USBFS_DEBUG_midi.h"
#include "USBFS_DEBUG_pvt.h"
#include "USBFS_DEBUG_cydmac.h"
#include "USBFS_DEBUG_msc.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_DEBUG_IntClock.h"
#include "UART_SBC_IntClock.h"
#include "USBFS_DEBUG_Dm_aliases.h"
#include "USBFS_DEBUG_Dm.h"
#include "USBFS_DEBUG_Dp_aliases.h"
#include "USBFS_DEBUG_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

