/* adc_balanced.c */

#include "adc_balanced.h"

/* ---- Internal state ---- */
static volatile uint8 s_eoc_flag = 0;          /* set by ISR on EOC */
static volatile uint8 s_frame_ready = 0;       /* set when we finish channel N_CH-1 */
static volatile uint8 s_ch_idx = 0;            /* current mux channel index */
static volatile int16 s_counts[N_CH];          /* latest counts per channel */

/* ISR prototype generated by PSoC Creator conventions */
CY_ISR_PROTO(isr_adc_Handler);

/* ISR: fires on ADC end-of-conversion */
CY_ISR(isr_adc_Handler)
{
    /* Clear pending IRQ from ISR component */
    isr_adc_ClearPending();
    s_eoc_flag = 1u;
}

void adc_balanced_init(void)
{
    CyGlobalIntEnable;

    /* Start hardware blocks */
    ADC_DelSig_1_Start();
    AMux_1_Start();

    /* Hook ISR */
    isr_adc_StartEx(isr_adc_Handler);

    /* Init state */
    s_ch_idx = 0u;
    s_eoc_flag = 0u;
    s_frame_ready = 0u;

    for (uint8 i = 0u; i < (uint8)N_CH; i++)
        s_counts[i] = 0;

    /* Start on channel 0 */
    AMux_1_Select(0u);

    /* Start conversions */
    ADC_DelSig_1_StartConvert();
}

static void adc_balanced_advance_on_eoc(void)
{
    /* Stop conversion before switching mux (cleanest/safest) */
    ADC_DelSig_1_StopConvert();

    /* Read result for current channel */
    s_counts[s_ch_idx] = ADC_DelSig_1_GetResult16();

    /* If we just captured the last channel, mark a full frame ready */
    if (s_ch_idx == (uint8)(N_CH - 1u))
    {
        s_frame_ready = 1u;
        s_ch_idx = 0u;
    }
    else
    {
        s_ch_idx++;
    }

    /* Switch mux to next channel */
    AMux_1_Select(s_ch_idx);

    /* (Optional) small settle; usually not required with DelSig, but available:
     * CyDelayUs(5);
     */

    /* Restart conversion */
    ADC_DelSig_1_StartConvert();
}

uint8 adc_balanced_poll_frame(int16 out_counts[N_CH])
{
    /* Consume EOC events (could be 0 or 1 per call; loop defensively) */
    if (s_eoc_flag)
    {
        s_eoc_flag = 0u;
        adc_balanced_advance_on_eoc();
    }

    if (s_frame_ready)
    {
        s_frame_ready = 0u;

        for (uint8 i = 0u; i < (uint8)N_CH; i++)
            out_counts[i] = s_counts[i];

        return 1u;
    }

    return 0u;
}

void adc_balanced_get_latest(int16 out_counts[N_CH])
{
    for (uint8 i = 0u; i < (uint8)N_CH; i++)
        out_counts[i] = s_counts[i];
}

int32 adc_balanced_counts_to_mv(int16 counts)
{
    /* ADC_DelSig_1_CountsTo_mVolts returns int32 in PSoC Creator */
    return (int32)ADC_DelSig_1_CountsTo_mVolts(counts);
}

void adc_balanced_clear_frame_flag(void)
{
    s_frame_ready = 0u;
}

/* [] END OF FILE */
